<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Supplier;

class Supplier2Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		/* `elrecove_posrecovecos`.`table_supplier` */
$table_supplier = [
	['id' => 1, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 7, 'is_active' => 1, 'commission_percentage' => 0],
['id' => 9, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 40, 'is_active' => 1, 'commission_percentage' => 30],
['id' => 41, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 52, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 59, 'is_active' => 1, 'commission_percentage' => 0],
['id' => 69, 'is_active' => 1, 'commission_percentage' => 20],
['id' => 71, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 72, 'is_active' => 1, 'commission_percentage' => 6],
['id' => 86, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 98, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 109, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 123, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 129, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 151, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 152, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 181, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 182, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 189, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 197, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 198, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 200, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 201, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 209, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 212, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 215, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 221, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 224, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 226, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 234, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 239, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 244, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 245, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 246, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 247, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 249, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 256, 'is_active' => 1, 'commission_percentage' => 0],
['id' => 258, 'is_active' => 1, 'commission_percentage' => 0],
['id' => 259, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 262, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 264, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 265, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 266, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 269, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 270, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 271, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 274, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 275, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 277, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 278, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 280, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 281, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 282, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 283, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 284, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 286, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 287, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 288, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 289, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 290, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 291, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 292, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 293, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 294, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 295, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 296, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 297, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 298, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 300, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 301, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 302, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 304, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 305, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 306, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 307, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 309, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 312, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 313, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 314, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 315, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 317, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 318, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 319, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 320, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 321, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 323, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 324, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 325, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 326, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 327, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 328, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 329, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 330, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 331, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 332, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 333, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 335, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 336, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 337, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 338, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 339, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 340, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 341, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 342, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 343, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 344, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 345, 'is_active' => 1, 'commission_percentage' => 20],
['id' => 346, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 347, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 348, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 349, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 350, 'is_active' => 1, 'commission_percentage' => 30],
['id' => 351, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 352, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 353, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 354, 'is_active' => 1, 'commission_percentage' => 0],
['id' => 355, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 356, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 357, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 358, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 359, 'is_active' => 1, 'commission_percentage' => 6],
['id' => 360, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 361, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 362, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 363, 'is_active' => 1, 'commission_percentage' => 0],
['id' => 364, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 365, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 366, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 367, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 368, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 369, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 370, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 371, 'is_active' => 1, 'commission_percentage' => 0],
['id' => 372, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 373, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 374, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 375, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 376, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 377, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 378, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 379, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 380, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 381, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 382, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 383, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 384, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 385, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 386, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 387, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 388, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 389, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 390, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 391, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 392, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 393, 'is_active' => 1, 'commission_percentage' => 0],
['id' => 394, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 395, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 396, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 397, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 398, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 399, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 400, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 401, 'is_active' => 0, 'commission_percentage' => 12],
['id' => 402, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 403, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 404, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 405, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 406, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 407, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 408, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 409, 'is_active' => 1, 'commission_percentage' => 12],
['id' => 410, 'is_active' => 1, 'commission_percentage' => 0],
['id' => 411, 'is_active' => 1, 'commission_percentage' => 100],
['id' => 412, 'is_active' => 1, 'commission_percentage' => 100],

];

		foreach ($table_supplier as $supplier){
			$s = Supplier::find($supplier['id']);
			$s->is_active = $supplier['is_active'];
			$s->commission_percentage = $supplier['commission_percentage'];
			$s->save();
		}

    }
}
